### ISSUE TITLE
Unable to install sqitch properly for mac

### ISSUE THREAD

**Issue by RutujaMGholap** [sqitchers/sqitch#559]
Can't locate Hash/Merge.pm in @INC (you may need to install the Hash::Merge module) (@INC contains: /Users/rgholap/Downloads/App-Sqitch-v1.1.0/t/../lib /usr/local/Cellar/perl/5.32.0/lib/perl5/site_perl/5.32.0/darwin-thread-multi-2level /usr/local/Cellar/perl/5.32.0/lib/perl5/site_perl/5.32.0 /usr/local/Cellar/perl/5.32.0/lib/perl5/5.32.0/darwin-thread-multi-2level /usr/local/Cellar/perl/5.32.0/lib/perl5/5.32.0 /usr/local/lib/perl5/site_perl/5.32.0/darwin-thread-multi-2level /usr/local/lib/perl5/site_perl/5.32.0) at /Users/rgholap/Downloads/App-Sqitch-v1.1.0/t/../lib/App/Sqitch.pm line 10.
BEGIN failed--compilation aborted at /Users/rgholap/Downloads/App-Sqitch-v1.1.0/t/../lib/App/Sqitch.pm line 10.
Compilation failed in require at /Users/rgholap/Downloads/App-Sqitch-v1.1.0/t/sqitch line 14.
BEGIN failed--compilation aborted at /Users/rgholap/Downloads/App-Sqitch-v1.1.0/t/sqitch line 14.

**Comment by theory** [comment]
How did you install Sqitch? Homebrew? What does this print?

```
find /usr/local/Cellar/perl/5.32.0/lib/perl5/site_perl/5.32.0 -name Merge.pm
```

**Comment by RutujaMGholap** [comment]
Yes, I installed it using homebrew, following the steps given there. But it is taking lot of time for installation  process.

**Comment by RutujaMGholap** [comment]
I have cloned this repo sqitchers/sqitch , could you please guide for further installation steps fro Mac.

**Comment by RutujaMGholap** [comment]
I have followed the steps and tried to installed sqitch using Homebrew..
But get the following as output..please help
Updating Homebrew...
==> Tapping homebrew/core
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 889512 (delta 5), reused 9 (delta 4), pack-reused 889500
Receiving objects: 100% (889512/889512), 355.78 MiB | 176.00 KiB/s, done.
Resolving deltas: 100% (603114/603114), done.
Tapped 2 commands and 5450 formulae (5,764 files, 390.2MB).
Usage: brew install [options] formula|cask

Install a formula or cask. Additional options specific to a formula may be
appended to the command.

Unless HOMEBREW_NO_INSTALL_CLEANUP is set, brew cleanup will then be run for
the installed formulae or, every 30 days, for all formulae.

  -d, --debug                      If brewing fails, open an interactive
                                   debugging session with access to IRB or a
                                   shell inside the temporary build directory.
  -f, --force                      Install formulae without checking for
                                   previously installed keg-only or
                                   non-migrated versions. When installing
                                   casks, overwrite existing files (binaries
                                   and symlinks are excluded, unless
                                   originally from the same cask).
  -v, --verbose                    Print the verification and postinstall
                                   steps.
      --formula, --formulae        Treat all named arguments as formulae.
      --env                        If std is passed, use the standard build
                                   environment instead of superenv. If super
                                   is passed, use superenv even if the formula
                                   specifies the standard build environment.
      --ignore-dependencies        An unsupported Homebrew development flag to
                                   skip installing any dependencies of any
                                   kind. If the dependencies are not already
                                   present, the formula will have issues. If
                                   you're not developing Homebrew, consider
                                   adjusting your PATH rather than using this
                                   flag.
      --only-dependencies          Install the dependencies with specified
                                   options but do not install the formula
                                   itself.
      --cc                         Attempt to compile using the specified
                                   compiler, which should be the name of the
                                   compiler's executable, e.g. gcc-7 for GCC
                                   7. In order to use LLVM's clang, specify
                                   llvm_clang. To use the Apple-provided
                                   clang, specify clang. This option will
                                   only accept compilers that are provided by
                                   Homebrew or bundled with macOS. Please do
                                   not file issues if you encounter errors
                                   while using this option.
  -s, --build-from-source          Compile formula from source even if a
                                   bottle is provided. Dependencies will still
                                   be installed from bottles if they are
                                   available.
      --force-bottle               Install from a bottle if it exists for the
                                   current or newest version of macOS, even if
                                   it would not normally be used for
                                   installation.
      --include-test               Install testing dependencies required to
                                   run brew test formula.
      --HEAD                       If formula defines it, install the HEAD
                                   version, aka. master, trunk, unstable.
      --fetch-HEAD                 Fetch the upstream repository to detect if
                                   the HEAD installation of the formula is
                                   outdated. Otherwise, the repository's HEAD
                                   will only be checked for updates when a new
                                   stable or development version has been
                                   released.
      --keep-tmp                   Retain the temporary files created during
                                   installation.
      --build-bottle               Prepare the formula for eventual bottling
                                   during installation, skipping any
                                   post-install steps.
      --bottle-arch                Optimise bottles for the specified
                                   architecture rather than the oldest
                                   architecture supported by the version of
                                   macOS the bottles are built on.
      --display-times              Print install times for each formula at the
                                   end of the run.
  -i, --interactive                Download and patch formula, then open a
                                   shell. This allows the user to run
                                   ./configure --help and otherwise
                                   determine how to turn the software package
                                   into a Homebrew package.
  -g, --git                        Create a Git repository, useful for
                                   creating patches to the software.
      --cask, --casks              Treat all named arguments as casks.
      --[no-]binaries              Disable/enable linking of helper
                                   executables (default: enabled).
      --require-sha                Require all casks to have a checksum.
      --[no-]quarantine            Disable/enable quarantining of downloads
                                   (default: enabled).
      --skip-cask-deps             Skip installing cask dependencies.
      --appdir                     Target location for Applications (default:
                                   /Applications).
      --colorpickerdir             Target location for Color Pickers (default:
                                   ~/Library/ColorPickers).
      --prefpanedir                Target location for Preference Panes
                                   (default: ~/Library/PreferencePanes).
      --qlplugindir                Target location for QuickLook Plugins
                                   (default: ~/Library/QuickLook).
      --mdimporterdir              Target location for Spotlight Plugins
                                   (default: ~/Library/Spotlight).
      --dictionarydir              Target location for Dictionaries (default:
                                   ~/Library/Dictionaries).
      --fontdir                    Target location for Fonts (default:
                                   ~/Library/Fonts).
      --servicedir                 Target location for Services (default:
                                   ~/Library/Services).
      --input-methoddir            Target location for Input Methods (default:
                                   ~/Library/Input Methods).
      --internet-plugindir         Target location for Internet Plugins
                                   (default: ~/Library/Internet Plug-Ins).
      --audio-unit-plugindir       Target location for Audio Unit Plugins
                                   (default:
                                   ~/Library/Audio/Plug-Ins/Components).
      --vst-plugindir              Target location for VST Plugins (default:
                                   ~/Library/Audio/Plug-Ins/VST).
      --vst3-plugindir             Target location for VST3 Plugins (default:
                                   ~/Library/Audio/Plug-Ins/VST3).
      --screen-saverdir            Target location for Screen Savers (default:
                                   ~/Library/Screen Savers).
      --language                   Comma-separated list of language codes to
                                   prefer for cask installation. The first
                                   matching language is used, otherwise it
                                   reverts to the cask's default language. The
                                   default value is the language of your
                                   system.
  -q, --quiet                      Make some output more quiet.
  -h, --help                       Show this message.
Error: invalid option: --with-snowflake-support

**Comment by theory** [comment]
With Homebrew, all you have to do is run these two commands:

```
brew tap sqitchers/sqitch
brew install sqitch --with-snowflake-support
```

I don't see these commands your paste above, which appears to be a usage statement from Homebrew itself.

Note that you need to have the SnowSQL client and ODBC driver installed to use Sqitch with snowflake. [Details here](/sqitchers/homebrew-sqitch#--with-snowflake-support).

**Comment by RutujaMGholap** [comment]
rgholap@C02DRB64MD6M ~ % brew tap sqitchers/sqitch      
Updating Homebrew...
To restore the stashed changes to /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core run:
  'cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core && git stash pop'
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 39 formulae.
==> Renamed Formulae
prest -> prestd

==> Tapping sqitchers/sqitch
Cloning into '/usr/local/Homebrew/Library/Taps/sqitchers/homebrew-sqitch'...
remote: Enumerating objects: 32, done.
remote: Counting objects: 100% (32/32), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 727 (delta 13), reused 27 (delta 9), pack-reused 695
Receiving objects: 100% (727/727), 146.05 KiB | 237.00 KiB/s, done.
Resolving deltas: 100% (417/417), done.
Tapped 7 formulae (40 files, 218.1KB).
rgholap@C02DRB64MD6M ~ % brew install sqitch --with-snowflake-support
Updating Homebrew...
==> Installing sqitch from sqitchers/sqitch
==> Downloading https://homebrew.bintray.com/bottles/libiodbc-3.52.13.catalina.bot
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/b9b78f823c2af7962bfc97c
######################################################################## 100.0%
==> Downloading https://www.cpan.org/authors/id/D/DW/DWHEELER/App-Sqitch-v1.1.0.ta
Already downloaded: /Users/rgholap/Library/Caches/Homebrew/downloads/f1ebd13dbda2c5ad95c6f9f14278d7771011f3d113aaa624d6fb79e78bd7fb3c--App-Sqitch-v1.1.0.tar.gz
==> Installing dependencies for sqitchers/sqitch/sqitch: libiodbc
==> Installing sqitchers/sqitch/sqitch dependency: libiodbc
==> Pouring libiodbc-3.52.13.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/libiodbc/3.52.13: 36 files, 1.7MB
==> Installing sqitchers/sqitch/sqitch --with-snowflake-support
==> cpanm --local-lib instutil --notest Menlo::CLI::Compat Module::Build
==> perl Build.PL --install_base /usr/local/Cellar/sqitch/v1.1.0 --etcdir /usr/loc
==> ./Build bundle





Error: SIGTERM
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:73:in `read'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:73:in `block (3 levels) in safe_fork'
/usr/local/Homebrew/Library/Homebrew/utils.rb:405:in `ignore_interrupts'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:63:in `block (2 levels) in safe_fork'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:34:in `open'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:34:in `block in safe_fork'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:33:in `safe_fork'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:912:in `build'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:466:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:388:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:301:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:299:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:299:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
rgholap@C02DRB64MD6M ~ % 
rgholap@C02DRB64MD6M ~ % 
rgholap@C02DRB64MD6M ~ % 
rgholap@C02DRB64MD6M ~ % 
rgholap@C02DRB64MD6M ~ % 
rgholap@C02DRB64MD6M ~ % Traceback (most recent call last):
	19: from /usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
	18: from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:299:in `install'
	17: from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:299:in `each'
	16: from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:301:in `block in install'
	15: from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:388:in `install_formula'
	14: from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:466:in `install'
	13: from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:912:in `build'
	12: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:33:in `safe_fork'
	11: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
	10: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:34:in `block in safe_fork'
	 9: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:34:in `open'
	 8: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:37:in `block (2 levels) in safe_fork'
	 7: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:37:in `fork'
	 6: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:42:in `block (3 levels) in safe_fork'
	 5: from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:924:in `block in build'
	 4: from /usr/local/Homebrew/Library/Homebrew/sandbox.rb:99:in `exec'
	 3: from /usr/local/Homebrew/Library/Homebrew/utils.rb:302:in `safe_system'
	 2: from /usr/local/Homebrew/Library/Homebrew/utils.rb:47:in `system'
	 1: from /usr/local/Homebrew/Library/Homebrew/utils.rb:38:in `_system'
/usr/local/Homebrew/Library/Homebrew/utils.rb:38:in `wait': SIGTERM (SignalException)
	16: from /usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
	15: from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:299:in `install'
	14: from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:299:in `each'
	13: from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:301:in `block in install'
	12: from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:388:in `install_formula'
	11: from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:466:in `install'
	10: from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:912:in `build'
	 9: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:33:in `safe_fork'
	 8: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
	 7: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:34:in `block in safe_fork'
	 6: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:34:in `open'
	 5: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:37:in `block (2 levels) in safe_fork'
	 4: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:37:in `fork'
	 3: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:38:in `block (3 levels) in safe_fork'
	 2: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:55:in `rescue in block (3 levels) in safe_fork'
	 1: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:55:in `puts'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:55:in `write': Broken pipe (Errno::EPIPE)
Traceback (most recent call last):
	23: from /usr/local/Homebrew/Library/Homebrew/build.rb:223:in `<main>'
	22: from /usr/local/Homebrew/Library/Homebrew/build.rb:134:in `install'
	21: from /usr/local/Homebrew/Library/Homebrew/utils.rb:531:in `with_env'
	20: from /usr/local/Homebrew/Library/Homebrew/build.rb:139:in `block in install'
	19: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1215:in `brew'
	18: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2236:in `stage'
	17: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
	16: from /usr/local/Homebrew/Library/Homebrew/resource.rb:91:in `stage'
	15: from /usr/local/Homebrew/Library/Homebrew/resource.rb:116:in `unpack'
	14: from /usr/local/Homebrew/Library/Homebrew/resource.rb:197:in `mktemp'
	13: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `run'
	12: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
	11: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
	10: from /usr/local/Homebrew/Library/Homebrew/resource.rb:121:in `block in unpack'
	 9: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2256:in `block in stage'
	 8: from /usr/local/Homebrew/Library/Homebrew/utils.rb:531:in `with_env'
	 7: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2257:in `block (2 levels) in stage'
	 6: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1222:in `block in brew'
	 5: from /usr/local/Homebrew/Library/Homebrew/build.rb:171:in `block (2 levels) in install'
	 4: from /usr/local/Homebrew/Library/Taps/sqitchers/homebrew-sqitch/Formula/sqitch.rb:105:in `install'
	 3: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2043:in `system'
	 2: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2043:in `open'
	 1: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2084:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2084:in `wait': SIGTERM (SignalException)
	2: from /usr/local/Homebrew/Library/Homebrew/build.rb:211:in `<main>'
	1: from /usr/local/Homebrew/Library/Homebrew/build.rb:244:in `rescue in <main>'
/usr/local/Homebrew/Library/Homebrew/build.rb:244:in `close': Broken pipe (Errno::EPIPE)

rgholap@C02DRB64MD6M ~ % 
rgholap@C02DRB64MD6M ~ % brew install sqitch --with-snowflake-support
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 1 formula.

Warning: sqitchers/sqitch/sqitch v1.1.0 is already installed, it's just not linked
You can use `brew link sqitch` to link this version.
rgholap@C02DRB64MD6M ~ % sqitch --version
zsh: command not found: sqitch
rgholap@C02DRB64MD6M ~ % brew link sqitch
Linking /usr/local/Cellar/sqitch/v1.1.0... 263 symlinks created
rgholap@C02DRB64MD6M ~ % sqitch --version
zsh: command not found: sqitch
rgholap@C02DRB64MD6M ~ % 






This is what I get after completing installation..
Why is sqitch command not working on terminal?
and is the installation done rightly??

**Comment by theory** [comment]
```
==> ./Build bundle

Error: SIGTERM

Please report this issue:
https://docs.brew.sh/Troubleshooting
```

Oof, this is bad. Something is going seriously wrong. I suggest you report the issue to the [troubleshooting URL](https://docs.brew.sh/Troubleshooting), as I have no idea what the issue could be. There will need to be some additional diagnostics…

**Comment by RutujaMGholap** [comment]
Ok..Thanks..I'll report it

**Comment by RutujaMGholap** [comment]
rgholap@C02DRB64MD6M ~ % brew doctor
Your system is ready to brew.
rgholap@C02DRB64MD6M ~ % brew update
Already up-to-date.
rgholap@C02DRB64MD6M ~ % brew install sqitch
Updating Homebrew...
==> Installing sqitch from sqitchers/sqitch
==> Downloading https://www.cpan.org/authors/id/D/DW/DWHEELER/App-Sqitch-v1.1.0.
Already downloaded: /Users/rgholap/Library/Caches/Homebrew/downloads/f1ebd13dbda2c5ad95c6f9f14278d7771011f3d113aaa624d6fb79e78bd7fb3c--App-Sqitch-v1.1.0.tar.gz
==> cpanm --local-lib instutil --notest Menlo::CLI::Compat Module::Build
==> perl Build.PL --install_base /usr/local/Cellar/sqitch/v1.1.0 --etcdir /usr/l
==> ./Build bundle

Last 15 lines from /Users/rgholap/Library/Logs/Homebrew/sqitch/03.Build:
OK
tar: Error opening archive: truncated gzip input
--> Working on Template
Fetching http://www.cpan.org/authors/id/A/AT/ATOOMIC/Template-Toolkit-3.009.tar.gz ... ! Failed to unpack DateTime-1.54.tar.gz: no directory
! Failed to fetch distribution DateTime-1.54
OK
tar: truncated gzip input
tar: Error exit delayed from previous errors.
! No MYMETA file is found after configure. Your toolchain is too old?
! The distribution doesn't have a proper Makefile.PL/Build.PL See /private/tmp/sqitch-20210119-11552-1v9t1yo/App-Sqitch-v1.1.0/.brew_home/.cpanm/work/1611039045.16332/build.log for details.
! Installing the dependencies failed: Module 'DateTime' is not installed, Module 'String::Formatter' is not installed, Module 'Locale::TextDomain' is not installed, Module 'Locale::Messages' is not installed, Module 'List::MoreUtils' is not installed, Module 'Sub::Exporter::Util' is not installed, Module 'Clone' is not installed, Module 'IO::Pager' is not installed, Module 'Pod::Find' is not installed, Module 'DBI' is not installed, Module 'Sub::Exporter' is not installed, Module 'Throwable' is not installed, Module 'StackTrace::Auto' is not installed
! Bailing out the installation for App-Sqitch-v1.1.0.
Error installing modules: 
Configuring Template-Toolkit-3.009 ... N/A
63 distributions installed

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/sqitchers/homebrew-sqitch/issues

These open issues may also help:
After brew install sqitch --with-postgres-support, error deploying https://github.com/sqitchers/homebrew-sqitch/issues/46
rgholap@C02DRB64MD6M ~ % 
rgholap@C02DRB64MD6M ~ % sqitch 
zsh: command not found: sqitch
rgholap@C02DRB64MD6M ~ % brew list
cpanminus	perl




please check what is the problem

**Comment by RutujaMGholap** [comment]
am facing the same problem
I tried installing it by command cpanm DBD::ODBC
But I get following result:
cpanm (App::cpanminus) 1.9018 on perl 5.032000 built for darwin-thread-multi-2level
Work directory is /Users/rgholap/.cpanm/work/1611137520.38841
You have make /usr/bin/make
You have /usr/bin/curl: curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2
You have /usr/bin/tar: bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.6
You have /usr/bin/unzip
Searching DBD::ODBC () on cpanmetadb ...
--> Working on DBD::ODBC
Fetching http://www.cpan.org/authors/id/M/MJ/MJEVANS/DBD-ODBC-1.61.tar.gz
-> OK
Unpacking DBD-ODBC-1.61.tar.gz
Entering DBD-ODBC-1.61
Checking configure dependencies from META.yml
Checking if you have DBI 1.21 ... Yes (1.643)
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (7.44)
Configuring DBD-ODBC-1.61
Running Makefile.PL

Remember to actually *READ* the README file!
And re-read it if you have any problems.
OSNAME: darwin
LANG:
ODBCHOME: /opt/snowflake/snowflakeodbc/lib/universal/libSnowflake.dylib:
LD_LIBRARY_PATH:
DBROOT:
WINDIR:
II_SYSTEM:
DBD_ODBC_UNICODE:
Perl: 5.032000
ExtUtils::MakeMaker: 7.44
Command line options:
u! = undef
x! = undef
o=s =
g! = 0
w! = undef
e! = undef

You are using a Perl configured with threading enabled.
Please read the warnings in DBI about this.

You should also be aware that on non-Windows platforms ODBC drivers come
in two forms, thread-safe and non-thread-safe drivers and you may need
to make sure you are using the right one.

Press return to continue...
Looking for odbc_config in : /opt/snowflake/snowflakeodbc/lib/universal/libSnowflake.dylib:
Looking for odbc_config at /opt/snowflake/snowflakeodbc/lib/universal/libSnowflake.dylib:/bin/odbc_config
Looking for odbc_config in (PATH) /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
odbc_config not found
Looking for iodbc-config in PATH /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
iodbc_config not found
odbc_config not found - ok, there are other things I can do
Still trying to guess ODBCHOME - looking for headers now
trying /opt/snowflake/snowflakeodbc/lib/universal/libSnowflake.dylib:/include
trying /usr/include
trying /usr/local/include
trying /usr/pkg/include
trying /usr/local/easysoft/unixODBC/include

I cannot find driver manager header files. Perhaps you need to install the
unixodbc-dev package or the iodbc-dev package

The DBD::ODBC module needs to link with an ODBC 'Driver Manager'.
(The Driver Manager, in turn, needs one or more database specific ODBC
drivers. The DBD::ODBC module does not include any ODBC drivers!)

You need to indicate where your ODBC Driver Manager is installed.
You can do this by:

o setting the ODBCHOME environment variable
o running 'perl Makefile.PL -o odbcdir'
o adding path to odbc_config/iodbc_config to PATH

If you do not have an ODBC Driver Manager you should try to get hold of
the unixODBC packages for your system or build it from source (see
http://www.unixodbc.org). If you install driver manager packages you
need to include the "XXX-dev" package which includes the C header files.
-> N/A
-> FAIL No MYMETA file is found after configure. Your toolchain is too old?
-> FAIL Configure failed for DBD-ODBC-1.61. See /Users/rgholap/.cpanm/work/1611137520.38841/build.log for details.

Please help me overcoming it, and I have ODBC driver and iodbc set up well

**Comment by theory** [comment]
You need to tell DBD::ODBC where to find the ODBC driver manager. Have you installed unixODBC or libiodbc? You'll need to tell perl where to find the files, probably by setting the ODBCHOME environment variable to point to the root directory for the driver manager.

**Comment by theory** [comment]
Did you ever get this issue resolved, @RutujaMGholap?

**Comment by theory** [comment]
Closing due to inactivity.
