### ISSUE TITLE
Snowflake Sqitch errors with "password is empty" despite key authentication.

### ISSUE THREAD

**Issue by jperkelens** [sqitchers/sqitch#574]
Not sure if this belongs here or in https://github.com/sqitchers/sqitch proper but, when trying to run sqitch with private key authentication in a image built for snowflake, scripts are failing with the following:

```
Deploying changes to db:snowflake://<SNIP>/sqitch?Driver=Snowflake;warehouse=Deployment;authenticator=SNOWFLAKE_JWT;uid=SVC_DEPLOY;priv_key_file=/ssh/snowflake.p8;role=ACCOUNTADMIN;priv_key_file_pwd=<SNIP>;database=SQITCH
  + AddVindexDb .. 251006 (n/a): Password is empty
not ok
"snowsql" unexpectedly returned exit value 5
Deploy failed
```

This is similar to some errors reported in sqitchers/docker-sqitch#39 . What is puzzling to me is that im able to see a session created in the Snowflake admin console so im not sure what this error is referring to (see attached image). Any guidance on what's going wrong here would be appreciated. Happy to provide more info as needed.

<img width="1426" alt="Screen Shot 2021-04-22 at 5 45 20 PM" src="https://user-images.githubusercontent.com/176702/115859319-0670ab80-a3fe-11eb-9f3f-e695a321a451.png">

**Comment by theory** [comment]
Started looking into this, and I have to admit I'm confused by this error:

```
  + AddVindexDb .. 2,51006 (n/a): Password is empty
```

Is that coming from SnowSQL. Seems like it, since it's `snowsql` that exits with an error. But of course the password is empty. In fact, Sqitch never passes a password. Instead, it sets the `SNOWSQL_PWD` environment variable only if there is a password. By putting a password in the  snowsql config file, SnowSQL finds it and uses it.

It sounds to me like a bug in SnowSQL, such that it reported a lack of password when using `SNOWFLAKE_JWT`. It should not do that, since it does not use the password for `SNOWFLAKE_JWT` auth, right? Does the issue persist if you upgrade SnowSQL? I don't see anything in the [release notes](https://community.snowflake.com/articles/Product_Update/client-release-history), so I'm dubious. But it's pretty clearly not a Sqitch issue here, since SnowSQL reads directly from its config file; Sqitch only reads it to pass params to ODBC.

**Comment by bhawnatyagi** [comment]
I am getting the same error "Password not empty" even though I have added password in snowsql config file. My sqitch deploy command is still failing with below error:

251006 (n/a): Password is empty
"/Applications/SnowSQL.app/Contents/MacOS/snowsql" unexpectedly returned exit value 5

Any help would be appreciated.

**Comment by theory** [comment]
What does your snowsql config file look like, @bhawnatyagi?

**Comment by bhawnatyagi** [comment]
Below is the screenshot of the snowsql config. I am accessing it from my user directory.
<img width="1411" alt="Screen Shot 2022-02-05 at 12 43 06 PM" src="https://user-images.githubusercontent.com/96139610/152658319-b6b78a84-ae78-47b9-a21c-26da7df857cf.png">

**Comment by bhawnatyagi** [comment]
Now, I am getting below error when I am trying to deploy my changes via sqitch:
sqitch deploy 'db://<accountname.snowflakecomputing.com>/<dbname>/Driver=<drivername>;warehouse=<warehousename>;pwd=<password_mentioned_above>;UID=<user_mentioned_above>'

Adding registry tables to  db://<accountname.snowflakecomputing.com>/<dbname>/Driver=<drivername>;warehouse=<warehousename>;pwd=<password_mentioned_above>;UID=<user_mentioned_above>
"/Applications/SnowSQL.app/Contents/MacOS/snowsql" unexpectedly returned exit value 247

When I checked the log file snowsql_rt.log, I can see that the command is still failing with "Password is empty" error. Is there any way to check for snowsql exit code? Any list of exit codes available which makes it easy to debug the issue?

**Comment by theory** [comment]
It looks like everything is commented-out. Check out the example `~/.snowsql/config` file [here](http://sqitch.org/docs/manual/sqitch-authentication/#use-a-password-file) (scroll down to the "Snowflake" bullet).

**Comment by bhawnatyagi** [comment]
Thanks for the quick response. It was working fine before when I didn't provide username and password with everything commented out. I will give it a try but would be good to know why it was working before and not now?

**Comment by theory** [comment]
Ah, you had not mentioned that it worked before. What changed?

**Comment by bhawnatyagi** [comment]
Just added user name and password now. Actually sqitch deploy moved ahead with changes as shown below but then again failed:

sqitch deploy 'db://<accountname.snowflakecomputing.com>//Driver=;warehouse=;pwd=<password_mentioned_above>;UID=<user_mentioned_above>'
Deploying changes through pre_landing/tasks/create_load_prod_api_ana_885 @ANA_885 to db://<accountname.snowflakecomputing.com>//Driver=;warehouse=;pwd=<password_mentioned_above>;UID=<user_mentioned_above>

+ pre_landing/tasks/create_load_prod_api_ana_885 @ANA_885 .. not ok
"/Applications/SnowSQL.app/Contents/MacOS/snowsql" unexpectedly returned exit value 247

Deploy failed

**Comment by bhawnatyagi** [comment]
This is the error stack trace that I can see right now from snowsql_rt_log:

2022-02-05 00:01:33,839 (6589/MainThread) snowflake.cli.common.config DEBUG         config:87   - Reading cnf: /Users/btyagi/.sno$
2022-02-05 00:01:33,840 (6589/MainThread) snowflake.cli.common.config DEBUG         config:87   - Reading cnf: /etc/snowsql.cnf
2022-02-05 00:01:33,840 (6589/MainThread) snowflake.cli.common.config DEBUG         config:87   - Reading cnf: /etc/snowflake/sno$
2022-02-05 00:01:33,840 (6589/MainThread) snowflake.cli.common.config DEBUG         config:87   - Reading cnf: /usr/local/etc/sno$
2022-02-05 00:01:33,841 (6589/MainThread) snowflake.cli.common.config DEBUG         config:87   - Reading cnf: /Users/btyagi/.sno$
2022-02-05 00:01:33,841 (6589/MainThread) snowflake.cli.common.config DEBUG         config:87   - Reading cnf: /Users/btyagi/.sno$
2022-02-05 00:01:33,842 (6589/MainThread) __main__ DEBUG      eventloop:353  - [None, None, None, None, None, None, None, None, N$
2022-02-05 00:01:33,842 (6589/MainThread) __main__ DEBUG      eventloop:359  - fallback to config values only if user did not spe$
2022-02-05 00:01:33,842 (6589/MainThread) __main__ DEBUG      eventloop:407  - host=None, port: + None
2022-02-05 00:01:33,842 (6589/MainThread) __main__ DEBUG      eventloop:446  - prompting user, password and account if still miss$
2022-02-05 00:01:33,842 (6589/MainThread) __main__ DEBUG      eventloop:501  - init sqlexecute
2022-02-05 00:01:33,842 (6589/MainThread) snowflake.cli.sqlexecute DEBUG     sqlexecute:254  - Connection DB Params: database: kd$
2022-02-05 00:01:33,843 (6589/MainThread) snowflake.connector.connection INFO     connection:272  - Snowflake Connector for Pytho$
2022-02-05 00:01:33,843 (6589/MainThread) snowflake.connector.connection DEBUG     connection:489  - connect
2022-02-05 00:01:33,843 (6589/MainThread) snowflake.connector.connection DEBUG     connection:754  - __config
2022-02-05 00:01:33,844 (6589/MainThread) __main__ ERROR      eventloop:547  - Database connection failed: 251006: 251006: Passwo$
Traceback (most recent call last):
  File "eventloop.py", line 540, in connect
  File "sqlexecute.py", line 296, in push_connection
  File "__init__.py", line 50, in Connect
  File "connection.py", line 283, in __init__
  File "connection.py", line 491, in connect
  File "connection.py", line 864, in __config
  File "errors.py", line 276, in errorhandler_wrapper
  File "errors.py", line 330, in hand_to_other_handler
  File "errors.py", line 213, in default_errorhandler
snowflake.connector.errors.ProgrammingError: 251006: 251006: Password is empty

**Comment by bhawnatyagi** [comment]
Please let me know if you need some other details from my side.

**Comment by theory** [comment]
Weird that SnowSQL emits no error message. I do not know what error 257 means. Sqitch just shells out to `snowsql`, so it might be useful to see what options it uses. Try applying this patch and run it again to see how Sqitch calls it

``` patch
diff --git a/lib/App/Sqitch/Engine/snowflake.pm b/lib/App/Sqitch/Engine/snowflake.pm
index 77399617..caacaf41 100644
--- a/lib/App/Sqitch/Engine/snowflake.pm
+++ b/lib/App/Sqitch/Engine/snowflake.pm
@@ -436,6 +436,7 @@ sub run_handle {
 sub _run {
     my $self   = shift;
     my $sqitch = $self->sqitch;
+    $sqitch->debug_literal(join ' ', $self->snowsql, @_);
     my $pass   = $self->password or
         # Use capture and emit instead of _run to avoid a wayward newline in
         # the output.
```

Then you can run it yourself directly with the same options . Note that it will set `SNOWSQL_PWD` if it finds a password.

From your stack trace, it sure looks like it doesn't have the right credentials.

**Comment by bhawnatyagi** [comment]
Thanks, let me try this. Where will i find this snowflake.pm file?

**Comment by theory** [comment]
How did you install Sqitch?

**Comment by bhawnatyagi** [comment]
I installed Sqitch via link that i got from sqitch documentation. Once i downloaded sqitch, i followed all steps provided in snowflake-sqitch tutorial.

**Comment by bhawnatyagi** [comment]
I use mac so installed it via homebrew.

**Comment by theory** [comment]
The output of `which sqitch` will tell you were it is installed. It's likely in a `bin` folder; the Snowflake.pm folder will be somewhere in a `lib` folder.

**Comment by bhawnatyagi** [comment]
Thanks for your help. The solution above didn't work for me completely but I was able to resolve the issue by reinstalling snowsql and sqitch both. 

As I have resolved this issue, I am looking an answer for the question that I have posted here : https://github.com/sqitchers/sqitch/issues/606

Could you please help?

**Comment by ajetayrus** [comment]
Hi ,

Can anyone help me to resolve below issue with sqicth ?

![Image](https://github.com/user-attachments/assets/5bb0b045-cb5b-4ad4-8d03-b93658c37530)

**Comment by theory** [comment]
I got the `251006 (n/a): Password is empty` error as I worked to move the Sqitch workflow to use key pair auth. It took a bit, but I finally replicated it by removing the `private_key_path` from the SnowSQL config. Seems like without that config, it prompts for a password.

In working through it, I discovered that I was putting my configuration file in the wrong place. The CI workflow uses the [WORKSPACE variable](https://docs.snowflake.com/en/user-guide/snowsql-install-config#setting-the-download-directory-and-configuration-file-location) to customize where SnowSQL lives, and I was putting the config into `$WORKSPACE/config`, but it has to go into `$WORKSPACE/.snowsql/config`.

So I think the key is to make sure that you're setting `private_key_path` correctly and that SnowSQL can find it.
